name: Build and release English presentation
on:
  release:
    types: [published]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: presentation-en.tex
          args: |
            -lualatex --file-line-error --interaction=nonstopmode -shell-escape
          extra_system_packages: "py-pygments"
      - name: Upload presentation to release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./presentation-en.pdf
          asset_name: presentation-modern-python-development.pdf
          asset_content_type: application/pdf
